### ISSUE TITLE
Adding classes to input

### ISSUE THREAD

**Issue by KolbySisk** [mezoistvan/ng2-flatpickr#43]
Is there currently a way to add a class to the generated input?

I've tried the [flatpickr option altInputClass](https://flatpickr.js.org/options/) but that didn't work. Is this possible currently?

**Comment by dockleryxk** [comment]
The inputs get the following classes: ng2-flatpickr-input flatpickr-input

Could you not work with that or use that to programmatically add the classes you need?

**Comment by KolbySisk** [comment]
The architecture of the product I'm building requires me to add a class, similar to if I was using bootstrap. I guess I could use the class to programatically add it, but that's messy and not very future proof.

**Comment by KolbySisk** [comment]
So in my case I need to add a class directly to the input. I'm using a lib similar to bootstrap, and it requires me to add the class directly to the input to get the proper styling.

**Comment by ghiscoding** [comment]
Hello, I just started using the lib and I have the same problem too. I use Bootstrap 3 in our project and Bootstrap requires the class `form-control` and if I pass it to the component the resize happens on the wrapper instead of the actual input. I also tried like @KolbySisk mentioned with `[config]="{ altInputClass: 'form-control' }"` and/or like this `altInputClass="form-control"` but that didn't do anything. 

The only patch I found, is to copy over the same CSS styling that bootstrap uses on the `form-control` class but also like @KolbySisk said, that is not very bullet proof. So current patch I have is this
```css
.ng2-flatpickr-input {
  display: block;
  width: 100%;
  height: 34px;
  padding: 6px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555555;
  background-color: #fff;
  background-image: none;
  border: 1px solid #ccc;
  border-radius: 4px;
  transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s, -webkit-box-shadow ease-in-out 0.15s;
}
```
I would rather do it the correct way, which would be to pass the class name somewhere which would get copied to the input.
